import { Language, ModuleData, Translation } from './types';

export const MODULES: ModuleData[] = [
  {
    id: 1,
    key: 'm1',
    icon: '📋',
    title: { en: 'Contract Risk Detection', zh: '法制審查：合約風險偵測' },
    description: { en: 'Use AI to review contracts, detect risks, and rewrite problematic clauses.', zh: '使用 AI 審查合約、偵測風險並重寫問題條款。' },
    badge: { en: 'Contract Expert', zh: '合約專家' },
    color: '#1a56db',
    lightColor: '#e8f0fe',
  },
  {
    id: 2,
    key: 'm2',
    icon: '📊',
    title: { en: 'USR Impact Quantification', zh: 'USR 影響力量化' },
    description: { en: 'Convert university social responsibility activities into measurable metrics.', zh: '將大學社會責任活動轉化為可量化的指標。' },
    badge: { en: 'Impact Analyst', zh: '影響力分析師' },
    color: '#059669',
    lightColor: '#d1fae5',
  },
  {
    id: 3,
    key: 'm3',
    icon: '📢',
    title: { en: 'Media Amplification Strategy', zh: '媒體擴散策略' },
    description: { en: 'Use AI to improve headlines and generate compelling media content.', zh: '使用 AI 改善標題並生成引人注目的媒體內容。' },
    badge: { en: 'Media Strategist', zh: '媒體策略師' },
    color: '#f59e0b',
    lightColor: '#fef3c7',
  },
  {
    id: 4,
    key: 'm4',
    icon: '🔍',
    title: { en: 'Sentiment & Crisis Monitoring', zh: '輿情監測與危機管理' },
    description: { en: 'Use AI to analyze public sentiment and detect crisis signals.', zh: '使用 AI 分析公眾情緒並偵測危機信號。' },
    badge: { en: 'Crisis Manager', zh: '危機管理師' },
    color: '#7c3aed',
    lightColor: '#ede9fe',
  },
];

export const TRANSLATIONS: Translation = {
  landingTitle: { en: 'AI Power Workshop', zh: 'AI 實戰工作坊' },
  landingSubtitle: { en: 'Turn Your Work Into AI-Augmented Excellence', zh: '讓 AI 成為你最強的工作夥伴' },
  landingDescription: { 
    en: 'A hands-on, bilingual training experience designed for university administrative staff. Master AI tools and apply them to your real work — right now.', 
    zh: '專為大學行政人員設計的雙語 AI 實戰培訓。學習 AI 工具，並立即應用到您的真實工作中。' 
  },
  startLearning: { en: '🚀 Start Learning', zh: '🚀 開始學習' },
  personalizeTitle: { en: '👤 Personalize Your Experience', zh: '👤 個人化設定' },
  personalizeSub: { en: 'Tell us about yourself so we can tailor the examples to your role.', zh: '告訴我們您的背景，我們將根據您的職位調整案例。' },
  department: { en: 'Your Department', zh: '您的部門' },
  role: { en: 'Your Role', zh: '您的職位' },
  startWorkshop: { en: 'Start Workshop →', zh: '開始工作坊 →' },
  progress: { en: 'Progress', zh: '學習進度' },
  overview: { en: 'Overview', zh: '總覽' },
  finalReport: { en: 'Final Report', zh: '最終報告' },
  welcome: { en: 'Welcome to the AI Power Workshop', zh: '歡迎來到 AI 實戰工作坊' },
  welcomeSub: { en: "You're about to transform how you work. This workshop guides you through 4 powerful AI modules tailored to university administration.", zh: '您即將改變您的工作方式。本工作坊將引導您完成 4 個專為大學行政人員設計的 AI 模組。' },
  yourJourney: { en: 'Your Learning Journey', zh: '您的學習旅程' },
  yourBadges: { en: 'Your Badges', zh: '您的成就徽章' },
  beginModule: { en: '🚀 Begin Module', zh: '🚀 開始模組' },
  concept: { en: '📚 Concept', zh: '📚 概念' },
  aiTutor: { en: '🤖 AI Tutor', zh: '🤖 AI導師' },
  exercise: { en: '🎮 Exercise', zh: '🎮 練習' },
  simulation: { en: '⚡ Simulation', zh: '⚡ 模擬' },
  analyzeAI: { en: 'Analyze with AI', zh: 'AI分析' },
  generateMetrics: { en: 'Generate Impact Metrics', zh: '生成影響力指標' },
  generateMedia: { en: 'Generate Media Content', zh: '生成媒體內容' },
  generateCrisis: { en: 'Generate Crisis Response Plan', zh: '生成危機應對計畫' },
  copy: { en: '📋 Copy', zh: '📋 複製' },
  improve: { en: '✨ Improve', zh: '✨ 改善' },
  saveReport: { en: '💾 Save to Report', zh: '💾 儲存到報告' },
  saved: { en: '✓ Saved!', zh: '✓ 已儲存！' },
  completeModule: { en: 'Complete Module & Continue →', zh: '完成模組並繼續 →' },
  generateFinalReport: { en: 'Generate My Final Report →', zh: '生成我的最終報告 →' },
  previewReport: { en: 'Preview Report', zh: '預覽報告' },
  downloadTxt: { en: 'Download Report (.txt)', zh: '下載報告 (.txt)' },
  downloadPdf: { en: 'Download Report (.pdf)', zh: '下載報告 (.pdf)' },
  points: { en: 'pts', zh: '積分' },
  nextAiTutor: { en: 'Next: AI Tutor', zh: '下一步：AI 導師' },
  nextExercise: { en: 'Next: Exercise', zh: '下一步：練習' },
  nextSimulation: { en: 'Next: Simulation', zh: '下一步：模擬' },
  moduleComplete: { en: 'Module Complete!', zh: '模組完成！' },
  earnedBadge: { en: "You've earned the", zh: '您已獲得' },
  badgeSuffix: { en: 'badge and +100 points!', zh: '徽章與 +100 積分！' },
  aiResponse: { en: 'AI RESPONSE', zh: 'AI 回應' },
  aiOutputEditable: { en: 'AI Output (Editable)', zh: 'AI 輸出 (可編輯)' },
  askAiQuestion: { en: 'Ask a question to get an instant AI explanation', zh: '提出問題以獲得即時 AI 說明' },
  yourInput: { en: 'Your Input', zh: '您的輸入' },
  readyToCompile: { en: 'Ready to compile your results?', zh: '準備好彙整您的成果了嗎？' },
  compileSub: { en: "We'll take all your saved AI outputs and user edits to generate a comprehensive executive summary.", zh: '我們將彙整您所有儲存的 AI 輸出與使用者編輯內容，生成一份完整的執行摘要。' },
  totalScore: { en: 'Total Score', zh: '總分' },
  workshopSummary: { en: 'Workshop Completion Summary', zh: '工作坊完成摘要' },
  pointsEarned: { en: 'Points Earned', zh: '獲得積分' },
  badgesEarned: { en: 'Badges Earned', zh: '獲得徽章' },
  modulesDone: { en: 'Modules Done', zh: '完成模組' },
  aiReport: { en: 'AI Report', zh: 'AI 報告' },
  yourName: { en: 'Your Name', zh: '您的姓名' },
  enterName: { en: 'Enter your name', zh: '輸入您的姓名' },
  deptLegal: { en: 'Legal & Compliance Office', zh: '法制與合規辦公室' },
  deptResearch: { en: 'Research & Development Office', zh: '研究發展處' },
  deptMedia: { en: 'Media & Public Affairs', zh: '媒體與公共事務' },
  deptExec: { en: 'Executive Office', zh: '行政辦公室' },
  deptHR: { en: 'Human Resources', zh: '人事室' },
  deptAcademic: { en: 'Academic Affairs', zh: '教務處' },
  roleStaff: { en: 'Administrative Staff', zh: '行政人員' },
  roleSection: { en: 'Section Chief', zh: '科長' },
  roleDirector: { en: 'Director / Manager', zh: '主任 / 經理' },
  roleSpecialist: { en: 'Specialist', zh: '專員' },
};
